name: Build Check (Client)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [20.x]
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('client/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

    #   # https://github.com/remix-run/remix/discussions/8270
    #   - name: Publish to Cloudflare Pages
    #     uses: cloudflare/pages-action@1
    #     with:
    #       accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    #       apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #       projectName: portfolio
    #       directory:  ./client/public
    #       gitHubToken: ${{ secrets.GITHUB_TOKEN }}
    #       branch: main
    #       wranglerVersion: '3'
